n = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(n))
print('Só tem espaços? ', n.isspace())
print('É alfanumérico? ', n.isalnum())
print('É alfabético? ', n.isalpha())
print('É um número? ', n.isalnum())
print('Está somente minúsculo?? ', n.islower())
print('Dá pra imprimir? ', n.isprintable())
print('Está capitalizada? ', n.istitle())
print('Está somente maiúsculo?', n.isupper())
print('É decimal? ', n.isdecimal())
print('É um dígito?', n.isdigit())
print('É identificador? ', n.isidentifier())
